# Generated by Django 4.2.30 on 2026-08-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_time', models.DateTimeField(auto_now_add=True)),
                ('total_signatures', models.IntegerField(default=0)),
                ('total_verifications', models.IntegerField(default=0)),
                ('total_incidents', models.IntegerField(default=0)),
                ('avg_qber', models.FloatField(default=0.0)),
                ('avg_fidelity', models.FloatField(default=1.0)),
            ],
        ),
    ]
