# Generated by Django 4.2.30 on 2026-08-29 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantumDigitalSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_id', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('message_digest', models.CharField(max_length=64)),
                ('payload_summary', models.TextField()),
                ('quantum_state_basis', models.CharField(default='|+>', max_length=20)),
                ('bell_pair_type', models.CharField(default='PHI_PLUS', max_length=20)),
                ('quantum_execution_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('VERIFIED', 'Verified Secure'), ('COMPROMISED', 'Threat Compromised'), ('EXPIRED', 'Expired')], default='ISSUED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_signatures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
