# Generated by Django 4.2.30 on 2026-08-29 06:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('qds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantumdigitalsignature',
            name='consumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quantumdigitalsignature',
            name='is_consumed',
            field=models.BooleanField(default=False, help_text='True if signature teleportation state has been verified/consumed.'),
        ),
        migrations.AddField(
            model_name='quantumdigitalsignature',
            name='message_payload',
            field=models.TextField(blank=True, default='', help_text='Canonical document payload message.'),
        ),
        migrations.AddField(
            model_name='quantumdigitalsignature',
            name='nonce',
            field=models.CharField(db_index=True, default=uuid.uuid4, help_text='Freshness cryptographic nonce.', max_length=64),
        ),
        migrations.AddField(
            model_name='quantumdigitalsignature',
            name='session_id',
            field=models.CharField(default=uuid.uuid4, max_length=64),
        ),
        migrations.AlterField(
            model_name='quantumdigitalsignature',
            name='message_digest',
            field=models.CharField(help_text='SHA-256 integrity hash digest.', max_length=64),
        ),
        migrations.AlterField(
            model_name='quantumdigitalsignature',
            name='payload_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
