# Generated by Django 6.1 on 2026-08-30 13:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qds', '0002_quantumdigitalsignature_consumed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SigningRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('purpose', models.CharField(default='Document Sign', max_length=255)),
                ('payload_content', models.TextField(blank=True, default='')),
                ('verifiers_count', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_signatures', to=settings.AUTH_USER_MODEL)),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signing_request', to='qds.quantumdigitalsignature')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_signatures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
