# Generated by Django 4.2.30 on 2026-09-05 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('qds', '0003_signingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantumdigitalsignature',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to='documents.document'),
        ),
        migrations.AddField(
            model_name='signingrequest',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signing_requests', to='documents.document'),
        ),
    ]
