# Generated by Django 4.2.30 on 2026-08-29 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureVerificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_id', models.CharField(max_length=64, unique=True)),
                ('payload_provided', models.TextField()),
                ('hash_match', models.BooleanField(default=True)),
                ('quantum_fidelity', models.FloatField(default=1.0)),
                ('qber', models.FloatField(default=0.0)),
                ('forgery_probability', models.FloatField(default=0.0)),
                ('threat_detected', models.BooleanField(default=False)),
                ('threat_category', models.CharField(blank=True, default='NONE', max_length=100)),
                ('verification_result', models.CharField(choices=[('PASSED', 'Verification Passed'), ('REJECTED_DIGEST_MISMATCH', 'Rejected: Digest Mismatch'), ('REJECTED_QUANTUM_THREAT', 'Rejected: Quantum Threat Breach'), ('UNAUTHORIZED', 'Rejected: Unauthorized Attempt')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='qds.quantumdigitalsignature')),
                ('verifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
