# Generated by Django 4.2.30 on 2026-08-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttackSimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_id', models.CharField(max_length=64, unique=True)),
                ('attack_vector', models.CharField(choices=[('FORGERY', 'Signature Forgery Attack'), ('IMPERSONATION', 'Sender Impersonation Attack'), ('REPLAY', 'Replay Attack'), ('CHANNEL_MANIPULATION', 'Quantum Channel Manipulation Attack'), ('UNAUTHORIZED_VERIFICATION', 'Unauthorized Verification Attempt')], max_length=50)),
                ('intensity', models.FloatField(default=0.5)),
                ('shots', models.IntegerField(default=1024)),
                ('target_state', models.CharField(default='|+>', max_length=10)),
                ('qber_result', models.FloatField(default=0.0)),
                ('fidelity_result', models.FloatField(default=1.0)),
                ('forgery_probability', models.FloatField(default=0.0)),
                ('is_detected', models.BooleanField(default=True)),
                ('threat_category', models.CharField(default='NONE', max_length=100)),
                ('incident_number', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
