# Generated by Django 4.2.30 on 2026-08-29 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_number', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('SIGNATURE_FORGERY', 'Signature Forgery'), ('SENDER_IMPERSONATION', 'Sender Impersonation'), ('REPLAY_ATTACK', 'Replay Attack'), ('QUANTUM_CHANNEL_MANIPULATION', 'Quantum Channel Manipulation'), ('UNAUTHORIZED_VERIFICATION', 'Unauthorized Verification'), ('QUANTUM_ANOMALY_BREACH', 'Quantum Anomaly Breach')], max_length=100)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='HIGH', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Under Investigation'), ('MITIGATED', 'Mitigated'), ('RESOLVED', 'Resolved'), ('FALSE_POSITIVE', 'False Positive')], default='OPEN', max_length=30)),
                ('qber', models.FloatField(default=0.0)),
                ('fidelity', models.FloatField(default=1.0)),
                ('forgery_probability', models.FloatField(default=0.0)),
                ('description', models.TextField()),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
