# Generated by Django 4.2.30 on 2026-09-03 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('qds', '0003_signingrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityincident',
            name='classification',
            field=models.CharField(choices=[('CONFIRMED_THREAT', 'Confirmed Threat'), ('FALSE_POSITIVE', 'False Positive'), ('INCONCLUSIVE', 'Inconclusive')], default='INCONCLUSIVE', max_length=30),
        ),
        migrations.AddField(
            model_name='securityincident',
            name='detection_source',
            field=models.CharField(default='QDS Verification Engine', max_length=100),
        ),
        migrations.AddField(
            model_name='securityincident',
            name='evidence_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='securityincident',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_incidents', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='securityincident',
            name='related_signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_incidents', to='qds.quantumdigitalsignature'),
        ),
        migrations.AddField(
            model_name='securityincident',
            name='source_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='securityincident',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Under Investigation'), ('CONTAINED', 'Contained'), ('RESOLVED', 'Resolved'), ('FALSE_POSITIVE', 'False Positive'), ('CLOSED', 'Closed')], default='OPEN', max_length=30),
        ),
        migrations.CreateModel(
            name='InvestigationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='incidents.securityincident')),
            ],
        ),
    ]
