# Generated by Django 4.2.30 on 2026-08-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticalAnalysisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=64, unique=True)),
                ('execution_id', models.CharField(blank=True, default='', max_length=64)),
                ('shots', models.IntegerField(default=1024)),
                ('qber', models.FloatField(default=0.0)),
                ('fidelity', models.FloatField(default=1.0)),
                ('chi_square_stat', models.FloatField(default=0.0)),
                ('chi_square_pvalue', models.FloatField(default=1.0)),
                ('degrees_of_freedom', models.IntegerField(default=1)),
                ('is_hypothesis_rejected', models.BooleanField(default=False)),
                ('forgery_probability', models.FloatField(default=0.0)),
                ('sprt_log_likelihood', models.FloatField(default=0.0)),
                ('sprt_decision', models.CharField(default='ACCEPT_HONEST', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
