# Generated by Django 4.2.30 on 2026-08-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('SIGNER', 'Signer'), ('VERIFIER', 'Verifier'), ('SECURITY_ANALYST', 'Security Analyst')], default='SIGNER', max_length=30),
        ),
    ]
