# Generated by Django 4.2.30 on 2026-08-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usersession_stepuptoken_mfarecoverycode_mfachallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='browser',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='usersession',
            name='device_type',
            field=models.CharField(default='Desktop', max_length=50),
        ),
        migrations.AddField(
            model_name='usersession',
            name='location_hint',
            field=models.CharField(blank=True, default='Local Subnet', max_length=100),
        ),
        migrations.AddField(
            model_name='usersession',
            name='os',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='usersession',
            name='revocation_reason',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usersession',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
