# Generated by Django 4.2.30 on 2026-08-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatEvaluationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_id', models.CharField(max_length=64, unique=True)),
                ('execution_id', models.CharField(blank=True, default='', max_length=64)),
                ('threat_detected', models.BooleanField(default=False)),
                ('threat_category', models.CharField(blank=True, default='NONE', max_length=100)),
                ('severity', models.CharField(default='INFO', max_length=20)),
                ('rule_triggered', models.CharField(blank=True, default='', max_length=100)),
                ('qber_measured', models.FloatField(default=0.0)),
                ('fidelity_measured', models.FloatField(default=1.0)),
                ('forgery_probability', models.FloatField(default=0.0)),
                ('chi_square_pvalue', models.FloatField(default=1.0)),
                ('explanation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThresholdRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=100, unique=True)),
                ('metric_type', models.CharField(choices=[('QBER', 'Quantum Bit Error Rate'), ('FIDELITY', 'Quantum State Fidelity'), ('CHI_SQUARE_P', 'Chi-Square p-value'), ('FORGERY_PROB', 'Forgery Probability'), ('TRACE_DIST', 'Trace Distance')], max_length=50)),
                ('operator', models.CharField(choices=[('>', 'Greater Than'), ('<', 'Less Than'), ('>=', 'Greater/Equal'), ('<=', 'Less/Equal')], max_length=10)),
                ('threshold_value', models.FloatField()),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='HIGH', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
