# Generated by Django 4.2.30 on 2026-09-05 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('PDF', 'PDF Document'), ('DOCX', 'Word Document'), ('TXT', 'Text Document')], max_length=20)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('sha256_hash', models.CharField(db_index=True, help_text='Cryptographic SHA-256 hash of original file bytes', max_length=64)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Timestamp when Signer confirmed document review', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organizations.organization')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
