# Generated by Django 4.2.30 on 2026-08-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuantumExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_id', models.CharField(max_length=64, unique=True)),
                ('protocol_type', models.CharField(default='QDS_TELEPORTATION', max_length=50)),
                ('shots', models.IntegerField(default=1024)),
                ('qubit_count', models.IntegerField(default=3)),
                ('input_state_basis', models.CharField(default='Z', max_length=20)),
                ('input_state_symbol', models.CharField(default='|0>', max_length=10)),
                ('bell_state_type', models.CharField(default='PHI_PLUS', max_length=20)),
                ('classical_bits', models.CharField(blank=True, default='', max_length=10)),
                ('measurement_counts', models.JSONField(default=dict)),
                ('statevector_real', models.JSONField(default=list)),
                ('statevector_imag', models.JSONField(default=list)),
                ('fidelity', models.FloatField(default=1.0)),
                ('trace_distance', models.FloatField(default=0.0)),
                ('channel_noise_level', models.FloatField(default=0.0)),
                ('is_attack_injected', models.BooleanField(default=False)),
                ('attack_type', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
